app = 'westonsankey-payment-app'
primary_region = 'atl'

[build]

[build.args]
  API_ENDPOINT = "https://westonsankey-social-service.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  VITE_API_ENDPOINT = "https://westonsankey-social-service.fly.dev"