app = 'wessankey-social-app'
primary_region = 'atl'

[build]

[build.args]
  API_ENDPOINT = "https://wessankey-social-service.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
