# fly.toml app configuration file generated for westonsankey-csrf-app-b on 2025-02-23T21:50:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'westonsankey-csrf-app-b'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  MY_VARIABLE = "my_value"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
